### PR TITLE
to satisfy: Improve diffs and support asserting textContent.

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by papandreou** [comment]
The Travis failure seems bogus, any idea @Munter?

**Comment by Munter** [comment]
Looks like just a temporary glitch. Rerunning it worked

**Comment by Munter** [comment]
The changes look great. Thanks!

**Comment by Munter** [comment]
Published in 1.3.0

**Comment by sunesimonsen** [comment]
@Munter awesome, this plugin is tremendously useful. It is the first time I'm using it.

**Comment by sunesimonsen** [comment]
@Munter I was trying to achieve this: https://github.com/One-com/knockout.autocomplete/blob/master/test/knockout.autocomplete.spec.js#L37-L63 and ran into a very weird diff :-)

**Comment by Munter** [comment]
Seeing deep structures like that makes me want to enable html syntax in the comparison, like what @bruderstein is doing in https://github.com/bruderstein/unexpected-react-shallow

Unfortunately not as easy in actual dom versus virtual dom

**Comment by sunesimonsen** [comment]
@Munter I don't exactly understand what you mean, the html is syntax highlighted in the diff.

**Comment by Munter** [comment]
`expect(node, 'to render as', '<div class="foo">bar</div>');`

**Comment by sunesimonsen** [comment]
@Munter is it '<div class="foo">bar</div>' you want highlighted?

**Comment by sunesimonsen** [comment]
That assertion makes sense, it should parse the rhs as html and copy the lhs, trim and remove all empty text nodes and use `to equal`. Then I guess you'll get a nice diff.

**Comment by sunesimonsen** [comment]
@Munter sorry I completely misunderstood you - you want jsx in you your tests, with highlighting in you editor right?

**Comment by Munter** [comment]
Jsx, maybe. Html as a string might also be more readable. Means having to learn less of the specific syntax for the assertion

**Comment by sunesimonsen** [comment]
Maybe the new strings in es6 would work in combination with an editor extension:

```js
expect(node, 'to render as', html`<div class="foo">bar</div>`);
```

**Pull request merged**
