### PR TITLE
Update to Unexpected 10.27, use expect.child

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by papandreou** [comment]
Ping @Munter

**Comment by Munter** [comment]
Did the API change in a minor release? What's up with the `exportType` instead of `addType`?

**Comment by papandreou** [comment]
It's a new feature in Unexpected 10.27.0, `addType` still works as well.

**Comment by papandreou** [comment]
See https://github.com/unexpectedjs/unexpected/pull/377

**Comment by Munter** [comment]
Nice

**Comment by papandreou** [comment]
For unexpected-dom this would be a semver-major thing, though, as it no longer works with <10.27.

**Pull request merged**
