### PR TITLE
Implement <DOMTextNode> to [exhaustively] satisfy <regexp>

### PR DESCRIPTION
**Pull request by papandreou**
// cc @Munter

### CODE REVIEW

**Comment by Munter** [comment]
That's a nice improvement on both performance and output :)

**Comment by Munter** [comment]
I guess that this is a major version bump, since the output changed?

**Comment by papandreou** [comment]
I'd say patch or minor. Previously `expect(textNode, 'to satisfy', regexp)` would unconditionally throw, which (I believe) is a bug that nobody is likely to have relied on.

**Comment by Munter** [comment]
I'll release a patch

**Comment by Munter** [comment]
Released in v3.1.1

**Pull request merged**
